# SPDX-License-Identifier: LGPL-2.1-or-later

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: |
    (?x)^(
        src/Mod/AddonManager|
        src/Tools|
        tests/src|
        src/Mod/Assembly|
        src/Mod/Sketcher
    )
exclude: |
    (?x)^(
        .*vcproj.*|
        .*vcxproj.*
    )
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: mixed-line-ending
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
        -   id: black
            args: ['--line-length', '100']
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
        -   id: clang-format
