
blank_issues_enabled : false

contact_links:

-   about : Join the community on our Discord.
    name : ğŸ’¬â€‚ğ——ğ—¶ğ˜€ğ—°ğ—¼ğ—¿ğ—±
    url : https://discord.gg/w2cTKGzccC

-   about : Join the community on our Forum.
    name : ğŸ’¬â€‚ğ—™ğ—¼ğ—¿ğ˜‚ğ—º
    url : https://forum.freecad.org

-   about : Read on how FreeCAD is developed.
    name : ğŸ“•â€‚ğ—›ğ—®ğ—»ğ—±ğ—¯ğ—¼ğ—¼ğ—¸
    url : https://freecad.github.io/DevelopersHandbook

-   about : Look up information about FreeCAD.
    name : ğŸŒâ€‚ğ—ªğ—¶ğ—¸ğ—¶
    url : https://wiki.freecad.org
