name: freecad
channels:
- conda-forge
- conda-forge/label/pivy_rc
dependencies:
- conda-forge/noarch::conda-libmamba-solver==24.7.0
- libspnav                             # [linux]
- kernel-headers_linux-64              # [linux and x86_64]
- libdrm-cos7-x86_64                   # [linux and x86_64]
- libselinux-cos7-x86_64               # [linux and x86_64]
- libsepol-cos7-x86_64                 # [linux and x86_64]
- libx11-common-cos7-x86_64            # [linux and x86_64]
- libx11-cos7-x86_64                   # [linux and x86_64]
- libxau-cos7-x86_64                   # [linux and x86_64]
- libxcb-cos7-x86_64                   # [linux and x86_64]
- libxdamage-cos7-x86_64               # [linux and x86_64]
- libxext-cos7-x86_64                  # [linux and x86_64]
- libxfixes-cos7-x86_64                # [linux and x86_64]
- libxi-cos7-x86_64                    # [linux and x86_64]
- libxi-devel-cos7-x86_64              # [linux and x86_64]
- libxxf86vm-cos7-x86_64               # [linux and x86_64]
- mesa-dri-drivers-cos7-x86_64         # [linux and x86_64]
- mesa-libegl-cos7-x86_64              # [linux and x86_64]
- mesa-libegl-devel-cos7-x86_64        # [linux and x86_64]
- mesa-libgl-cos7-x86_64               # [linux and x86_64]
- mesa-libgl-devel-cos7-x86_64         # [linux and x86_64]
- pixman-cos7-x86_64                   # [linux and x86_64]
- sysroot_linux-64                     # [linux and x86_64]
- xorg-x11-server-common-cos7-x86_64   # [linux and x86_64]
- xorg-x11-server-xvfb-cos7-x86_64     # [linux and x86_64]
- kernel-headers_linux-aarch64         # [linux and aarch64]
- libdrm-cos7-aarch64                  # [linux and aarch64]
- libglvnd-cos7-aarch64                # [linux and aarch64]
- libglvnd-glx-cos7-aarch64            # [linux and aarch64]
- libselinux-cos7-aarch64              # [linux and aarch64]
- libsepol-cos7-aarch64                # [linux and aarch64]
- libx11-common-cos7-aarch64           # [linux and aarch64]
- libx11-cos7-aarch64                  # [linux and aarch64]
- libxau-cos7-aarch64                  # [linux and aarch64]
- libxcb-cos7-aarch64                  # [linux and aarch64]
- libxdamage-cos7-aarch64              # [linux and aarch64]
- libxext-cos7-aarch64                 # [linux and aarch64]
- libxfixes-cos7-aarch64               # [linux and aarch64]
- libxi-cos7-aarch64                   # [linux and aarch64]
- libxi-devel-cos7-aarch64             # [linux and aarch64]
- libxxf86vm-cos7-aarch64              # [linux and aarch64]
- mesa-dri-drivers-cos7-aarch64        # [linux and aarch64]
- mesa-khr-devel-cos7-aarch64          # [linux and aarch64]
- mesa-libegl-cos7-aarch64             # [linux and aarch64]
- mesa-libegl-devel-cos7-aarch64       # [linux and aarch64]
- mesa-libgbm-cos7-aarch64             # [linux and aarch64]
- mesa-libgl-cos7-aarch64              # [linux and aarch64]
- mesa-libgl-devel-cos7-aarch64        # [linux and aarch64]
- mesa-libglapi-cos7-aarch64           # [linux and aarch64]
- pixman-cos7-aarch64                  # [linux and aarch64]
- sysroot_linux-aarch64                # [linux and aarch64]
- xorg-x11-server-common-cos7-aarch64  # [linux and aarch64]
- xorg-x11-server-xvfb-cos7-aarch64    # [linux and aarch64]
- sed                                  # [unix]
- ccache
- clang-format
- cmake
- coin3d
- compilers
- conda
- conda-devenv
- debugpy
- doxygen
- eigen
- fmt
- freetype
- git
- gmsh
- graphviz
- hdf5
- libboost-devel
- libcxx
- mamba
- matplotlib
- ninja
- numpy
- occt
- openssl
- pcl
- pip
- conda-forge/label/pivy_rc::pivy
- pkg-config
- ply
- pre-commit
- pybind11
- pyside6
- python==3.12.*
- pyyaml
- qt6-main
- smesh
- swig
- vtk==9.2.6
- xerces-c
- yaml-cpp
- zlib
- zstd
