name: freecad
channels:
- conda-forge
dependencies:
- kernel-headers_linux-64              # [linux and x86_64]
- libdrm-cos6-x86_64                   # [linux and x86_64]
- libselinux-cos6-x86_64               # [linux and x86_64]
- libsepol-cos6-x86_64                 # [linux and x86_64]
- libx11-common-cos6-x86_64            # [linux and x86_64]
- libx11-cos6-x86_64                   # [linux and x86_64]
- libxau-cos6-x86_64                   # [linux and x86_64]
- libxcb-cos6-x86_64                   # [linux and x86_64]
- libxdamage-cos6-x86_64               # [linux and x86_64]
- libxext-cos6-x86_64                  # [linux and x86_64]
- libxfixes-cos6-x86_64                # [linux and x86_64]
- libxi-cos6-x86_64                    # [linux and x86_64]
- libxi-devel-cos6-x86_64              # [linux and x86_64]
- libxxf86vm-cos6-x86_64               # [linux and x86_64]
- mesa-dri-drivers-cos6-x86_64         # [linux and x86_64]
- mesa-dri1-drivers-cos6-x86_64        # [linux and x86_64]
- mesa-libegl-cos6-x86_64              # [linux and x86_64]
- mesa-libegl-devel-cos6-x86_64        # [linux and x86_64]
- mesa-libgl-cos6-x86_64               # [linux and x86_64]
- mesa-libgl-devel-cos6-x86_64         # [linux and x86_64]
- pixman-cos6-x86_64                   # [linux and x86_64]
- sysroot_linux-64                     # [linux and x86_64]
- xorg-x11-server-common-cos6-x86_64   # [linux and x86_64]
- xorg-x11-server-xvfb-cos6-x86_64     # [linux and x86_64]
- kernel-headers_linux-aarch64         # [linux and aarch64]
- libdrm-cos7-aarch64                  # [linux and aarch64]
- libglvnd-cos7-aarch64                # [linux and aarch64]
- libglvnd-glx-cos7-aarch64            # [linux and aarch64]
- libselinux-cos7-aarch64              # [linux and aarch64]
- libsepol-cos7-aarch64                # [linux and aarch64]
- libx11-common-cos7-aarch64           # [linux and aarch64]
- libx11-cos7-aarch64                  # [linux and aarch64]
- libxau-cos7-aarch64                  # [linux and aarch64]
- libxcb-cos7-aarch64                  # [linux and aarch64]
- libxdamage-cos7-aarch64              # [linux and aarch64]
- libxext-cos7-aarch64                 # [linux and aarch64]
- libxfixes-cos7-aarch64               # [linux and aarch64]
- libxi-cos7-aarch64                   # [linux and aarch64]
- libxi-devel-cos7-aarch64             # [linux and aarch64]
- libxxf86vm-cos7-aarch64              # [linux and aarch64]
- mesa-dri-drivers-cos7-aarch64        # [linux and aarch64]
- mesa-khr-devel-cos7-aarch64          # [linux and aarch64]
- mesa-libegl-cos7-aarch64             # [linux and aarch64]
- mesa-libegl-devel-cos7-aarch64       # [linux and aarch64]
- mesa-libgbm-cos7-aarch64             # [linux and aarch64]
- mesa-libgl-cos7-aarch64              # [linux and aarch64]
- mesa-libgl-devel-cos7-aarch64        # [linux and aarch64]
- mesa-libglapi-cos7-aarch64           # [linux and aarch64]
- pixman-cos7-aarch64                  # [linux and aarch64]
- sysroot_linux-aarch64                # [linux and aarch64]
- xorg-x11-server-common-cos7-aarch64  # [linux and aarch64]
- xorg-x11-server-xvfb-cos7-aarch64    # [linux and aarch64]
- sed                                  # [unix]
- boost
- boost-cpp
- cmake
- coin3d
- compilers
- conda-build
- conda-devenv
- conda-smithy
- debugpy
- doxygen
- eigen
- freetype
- gmsh
- graphviz
- hdf5
- libcxx<16
- matplotlib
- ninja
- numpy
- occt==7.6.3
- openssl==3.0.*
- pcl
- pip
- pivy
- pkg-config
- ply
- pre-commit
- pybind11
- pyside2
- python
- pyyaml
- qt
- qt-main
- qt-webengine
- six
- smesh==9.9
- swig
- vtk
- xerces-c
- yaml-cpp
- zlib
- pip:
  - ptvsd
