# This workflow warns and then closes issues that have had no activity for a
# specified amount of time. You can adjust the behavior by modifying this file.
# For more information, see:
#   https://github.com/marketplace/actions/close-stale-issues
#   https://github.com/actions/stale/blob/master/action.yml
#   https://github.com/actions/stale
---
name: 'Stale Issues'
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * *'  # Run at 00:00 UTC every day
  workflow_dispatch:

permissions:
  contents: read
  issues: write  # for actions/stale to close stale issues
  pull-requests: write # for actions/stale to close stale pull requests

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: 'ðŸ§¹ Tag & close stale unconfirmed bugs'
        id: stale_issues
        uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 60
          days-before-issue-close: 14
          days-before-pr-stale: -1
          days-before-pr-close: -1
          operations-per-run: 100  # max num of ops per run
          stale-issue-label: 'Status: Stale'
          close-issue-label: 'Status: Auto-closing'
          exempt-issue-labels: 'Status: Confirmed,Priority: High,Priority: Critical,Blocker,Type: Feature,no-auto-close'
          remove-stale-when-updated: true
          ascending: true
          stale-issue-message: |
            Hi! This issue hasnâ€™t seen activity in a while. If itâ€™s still relevant, please update to the latest FreeCAD weekly build [download here](https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds) to see if the problem is resolved.

            If the issue persists, let us know by adding a comment with any updates or details. Otherwise, weâ€™ll close this issue automatically in 14 days to keep our backlog tidy. Feel free to comment anytime to keep it open. Closed issues can always be reopened.
            Thanks for helping improve FreeCAD!

            Access additional [FreeCAD](https://freecad.org) resources:
              - **Forum**: https://forum.freecad.org
              - **Blog**: https://blog.freecad.org
              - **Wiki**: https://wiki.freecad.org

      - name: 'ðŸ§¹ Close stale requested feedback issues'
        id: awaiting_issues
        uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 20
          days-before-issue-close: 14
          days-before-pr-stale: -1
          days-before-pr-close: -1
          operations-per-run: 100  # max num of ops per run
          stale-issue-label: 'Status: Stale'
          close-issue-label: 'Status: Auto-closing'
          only-labels: 'Status: Needs feedback,Status: Needs test on dev version,Status: Needs steps to reproduce'
          remove-stale-when-updated: true
          ascending: true
          stale-issue-message: |
            Hi! This issue hasnâ€™t seen activity in a while despite the need for further feedback.
            If itâ€™s still relevant, please update to the latest FreeCAD weekly build [download here](https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds) to see if the problem is resolved.

            If the issue persists, let us know by adding a comment with any updates or details. Otherwise, weâ€™ll close this issue automatically in 14 days to keep our backlog tidy. Feel free to comment anytime to keep it open. Closed issues can always be reopened.
            Thanks for helping improve FreeCAD!

            Access additional [FreeCAD](https://freecad.org) resources:
              - **Forum**: https://forum.freecad.org
              - **Blog**: https://blog.freecad.org
              - **Wiki**: https://wiki.freecad.org

      - name: 'ðŸ§¹ Tag & close inactive issues'
        id: inactive_issues
        uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 190
          days-before-issue-close: 60
          days-before-pr-stale: -1
          days-before-pr-close: -1
          operations-per-run: 50  # max num of ops per run
          stale-issue-label: 'Status: Stale'
          close-issue-label: 'Status: Auto-closing'
          exempt-issue-labels: 'Priority: High,Priority: Critical,Blocker,Type: Feature,no-auto-close'
          remove-stale-when-updated: true
          ascending: true
          stale-issue-message: |
            Hi! This issue hasnâ€™t seen activity in a while. We automatically check each issue after 190 days without activity to keep the backlog tidy.
            If itâ€™s still relevant, please update to the latest FreeCAD weekly build [download here](https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds) to see if the issue is already resolved.

            If the issue is still relevant, let us know by adding a comment.
            Otherwise, weâ€™ll close this issue automatically in 60 days.

            Feel free to comment anytime to keep it open. Closed issues can always be reopened.
            Thanks for helping improve FreeCAD!

            Access additional [FreeCAD](https://freecad.org) resources:
              - **Forum**: https://forum.freecad.org
              - **Blog**: https://blog.freecad.org
              - **Wiki**: https://wiki.freecad.org

      - name: 'ðŸ§¹ Tag & close inactive PRs'
        id: inactive_pr
        uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: -1
          days-before-issue-close: -1
          days-before-pr-stale: 120
          days-before-pr-close: 60
          operations-per-run: 30  # max num of ops per run
          stale-pr-label: 'Status: Stale'
          close-pr-label: 'Status: Auto-closing'
          exempt-pr-labels: 'Needs backport,Priority: High,Priority: Critical,no-auto-close'
          remove-stale-when-updated: true
          ascending: true
          stale-pr-message: |
            Thanks for helping improve FreeCAD!
            This pull request hasnâ€™t seen activity in a while. We automatically check each PR after 120 days without activity to keep the repository tidy.

            If the PR is still relevant, let us know by adding a comment.
            Otherwise, weâ€™ll close this PR automatically in 60 days.

            If you would like to keep working on this pull request, we advice to rebase it on current main branch, ask feedback from users or maintainers and engage with the community to get it forward.
